default_real_learn – Fiats
default_real_learn Module Procedure
116 statements
Source File
module procedure default_real_learn pure module subroutine default_real_learn(self, mini_batches_arr, cost, adam, learning_rate, workspace) Interface →
Arguments
Type Intent Optional Attributes Name
class(neural_network_t), intent(inout) :: self
type(mini_batch_t), intent(in) :: mini_batches_arr(:)
real, intent(out), optional, allocatable :: cost(:)
logical, intent(in) :: adam
real, intent(in) :: learning_rate
type(workspace_t), intent(inout) :: workspace
Calls
Call graph
default_real_learn calls beta, call_assert_consistency, call_julienne_assert, default, expected_outputs, inputs, local, differentiate, evaluate, fully_allocated, input_output_pairs, num_hidden_layers, num_inputs, values, obeta, pair_cost, reduce, reduce_dcdb, reduce_dcdw