default_real_map_to_training_ranges – Fiats
default_real_map_to_training_ranges Module Procedure
7 statements
Source File
module procedure default_real_map_to_training_ranges elemental module function default_real_map_to_training_ranges(self, input_output_pair) result(normalized_input_output_pair) Interface →
Arguments
Type Intent Optional Attributes Name
class(trainable_network_t), intent(in) :: self
type(input_output_pair_t), intent(in) :: input_output_pair
Return Value type(input_output_pair_t)
Calls
Call graph
default_real_map_to_training_ranges calls expected_outputs, inputs, map_from_output_range, map_to_input_range