default_real_from_json – Fiats
default_real_from_json Module Procedure
64 statements
Source File
module procedure default_real_from_json impure elemental module function default_real_from_json(file_) result(neural_network)
Arguments
Type Intent Optional Attributes Name
type(file_t), intent(in) :: file_
Return Value type(neural_network_t)
Calls
Call graph
default_real_from_json calls call_assert_consistency, call_assert_describe, call_assert_diagnose, get_json_value, activation_name, strings, lines, count_layers, count_neurons, neural_network, to_json, string, string_t