default_real_infer_unmapped – Fiats
default_real_infer_unmapped Module Procedure
21 statements
Source File
module procedure default_real_infer_unmapped elemental module function default_real_infer_unmapped(self, inputs) result(outputs) Interface →
Arguments
Type Intent Optional Attributes Name
class(unmapped_network_t), intent(in) :: self
type(tensor_t), intent(in) :: inputs
Return Value type(tensor_t)
Calls
Call graph
default_real_infer_unmapped calls call_assert_consistency, matmul+b, evaluate, values