double_precision_to_json – Fiats
double_precision_to_json Module Procedure
64 statements
Source File
module procedure double_precision_to_json impure elemental module function double_precision_to_json(self) result(json_file) Interface →
Arguments
Type Intent Optional Attributes Name
class(neural_network_t(double_precision)), intent(in) :: self
Return Value type(file_t)
Calls
Call graph
double_precision_to_json calls call_assert_consistency, call_julienne_assert, file_t, to_json, lines, num_hidden_layers, num_inputs, num_outputs, string_t