double_precision_infer – Fiats
double_precision_infer Module Procedure
19 statements
Source File
module procedure double_precision_infer elemental module function double_precision_infer(self, inputs) result(outputs) Interface →
Arguments
Type Intent Optional Attributes Name
class(neural_network_t(double_precision)), intent(in) :: self
type(tensor_t(double_precision)), intent(in) :: inputs
Return Value type(tensor_t(double_precision))
Calls
Call graph
double_precision_infer calls call_assert_consistency, evaluate, map_from_training_range, map_to_training_range, values