double_precision_infer_unmapped – Fiats
double_precision_infer_unmapped Module Procedure
21 statements
Source File
module procedure double_precision_infer_unmapped elemental module function double_precision_infer_unmapped(self, inputs) result(outputs) Interface →
Arguments
Type Intent Optional Attributes Name
class(unmapped_network_t(double_precision)), intent(in) :: self
type(tensor_t(double_precision)), intent(in) :: inputs
Return Value type(tensor_t(double_precision))
Calls
Call graph
double_precision_infer_unmapped calls call_assert_consistency, matmul+b, evaluate, values