double_precision_from_json – Fiats
double_precision_from_json Module Procedure
62 statements
Source File
module procedure double_precision_from_json impure elemental module function double_precision_from_json(file) result(neural_network)
Arguments
Type Intent Optional Attributes Name
type(double_precision_file_t), intent(in) :: file
Return Value type(neural_network_t(double_precision))
Calls
Call graph
double_precision_from_json calls call_assert_consistency, call_assert_describe, call_assert_diagnose, get_json_value, activation_name, double_precision_lines, count_layers, count_neurons, neural_network, to_json, string, string_t