double_precision_construct_layer – Fiats
double_precision_construct_layer Module Procedure
23 statements
Source File
module procedure double_precision_construct_layer recursive module function double_precision_construct_layer(layer_lines, start) result(layer)
Arguments
Type Intent Optional Attributes Name
type(double_precision_string_t), intent(in) :: layer_lines(:)
integer, intent(in) :: start
Return Value type(layer_t(double_precision)), target
Calls
Call graph
double_precision_construct_layer calls call_assert_describe, call_assert_diagnose, next_allocated, next_pointer, weights, string