default_real_infer – Fiats
default_real_infer Interface
127 statements
Source File
interface
Called by
private elemental module function default_real_infer(self, inputs) result(outputs) Implementation →
Arguments
Type Intent Optional Attributes Name
class(neural_network_t), intent(in) :: self
type(tensor_t), intent(in) :: inputs
Return Value type(tensor_t)
Call graph
do_concurrent_time calls infer
double_precision_do_concurrent_time calls infer
elemental_time calls infer
openmp_time calls infer
write_read_query_infer calls infer
read_query_infer calls infer
concurrent_inferences calls do_concurrent_time, double_precision_do_concurrent_time, elemental_time, openmp_time
write_read_infer calls write_read_query_infer