concurrent_inferences – Fiats
concurrent_inferences Program
136 statements
Source File
Uses
julienne_m
assert_m
fiats_m
omp_lib
iso_fortran_env
This program demonstrates how to read a neural network from a JSON file and use the network to perform concurrent inferences.
Calls
Variables
Type Attributes Name Initial
type(command_line_t) :: command_line
integer :: i
type(tensor_t), allocatable :: inputs(:,:,:)
integer, parameter :: lat = 263
integer, parameter :: lev = 15
integer, parameter :: lon = 317
type(string_t) :: network_file_name
type(neural_network_t) :: neural_network
integer :: num_trials
type(tensor_t), allocatable :: outputs(:,:,:)
Functions
function do_concurrent_time()
Arguments
None
Return Value real(kind=real64)
function double_precision_do_concurrent_time()
Arguments
None
Return Value real(kind=real64)
function elemental_time()
Arguments
None
Return Value real(kind=real64)
function openmp_time()
Arguments
None
Return Value real(kind=real64)
function random_inputs()
Arguments
None
Return Value type(tensor_t), allocatable, (:,:,:)
function trials()
Arguments
None
Return Value integer
Subroutines
subroutine print_stats(label, x)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: label
real(kind=real64), intent(in) :: x(:)
Call graph
concurrent_inferences calls argument_present, flag_value, do_concurrent_time, double_precision_do_concurrent_time, elemental_time, openmp_time, print_stats, random_inputs, trials, string, string_t, t_dc, t_dp_dc, t_elem, t_omp
do_concurrent_time calls infer
double_precision_do_concurrent_time calls string, infer, num_inputs
elemental_time calls infer
openmp_time calls infer
random_inputs calls string, file_t, num_inputs
trials calls flag_value