learn_power_series – Fiats
learn_power_series Program
95 statements
Source File
Uses
fiats_m
power_series
julienne_m
This trains a neural network to learn the following six polynomial functions of its eight inputs.
Calls
Variables
Type Attributes Name Initial
type(command_line_t) :: command_line
type(string_t) :: final_network_file
Functions
pure function e(j, n) result(unit_vector)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: j
integer, intent(in) :: n
Return Value real, allocatable, (:)
function perturbed_identity_network(perturbation_magnitude) result(trainable_network)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: perturbation_magnitude
Return Value type(trainable_network_t)
Subroutines
subroutine output(neural_network, file_name)
Arguments
Type Intent Optional Attributes Name
class(neural_network_t), intent(in) :: neural_network
type(string_t), intent(in) :: file_name
Call graph
learn_power_series calls bin_t, bins, call_julienne_assert, cost, desired_outputs, first, flag_value, infer, input_output_pairs, inputs, shuffle, last, mini_batches, network_outputs, num_inputs, num_outputs, output_sizes, output, perturbed_identity_network, y, random_init, random_numbers, string, string_t, train, values, white_noise
output calls to_json, write_lines
perturbed_identity_network calls string_t, e
y calls call_julienne_assert, values