print_training_configuration – Fiats
print_training_configuration Program
10 statements
Source File
Uses
fiats_m
julienne_m
Demonstrate how to construct and print a training_configuration_t object
Calls
Call graph
print_training_configuration calls file_t, to_json, string_t, write_lines