train_and_write – Fiats
train_and_write Program
90 statements
Source File
Uses
assert_m
fiats_m
julienne_m
This program demonstrates how to train a simple neural network starting from a randomized initial condition and how to write the initial network and the trained network to separate JSON files. The network has two hiden layers. The input, hidden, and output layers are all two nodes wide. The training data has outputs that identically match the corresponding inputs. Hence, the desired network represents an identity mapping. With RELU activation functions, the desired network therefore contains weights corresponding to identity matrices and biases that vanish everywhere. The initial condition corresponds to the desired network with all weights and biases perturbed by a random variable that is uniformly distributed on the range [0,0.1].
Calls
Variables
Type Attributes Name Initial
type(command_line_t) :: command_line
type(string_t) :: final_network_file
Functions
pure function e(m, n) result(e_mn)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: m
integer, intent(in) :: n
Return Value real
function perturbed_identity_network(perturbation_magnitude) result(trainable_network)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: perturbation_magnitude
Return Value type(trainable_network_t)
Subroutines
subroutine output(neural_network, file_name)
Arguments
Type Intent Optional Attributes Name
class(neural_network_t), intent(in) :: neural_network
type(string_t), intent(in) :: file_name
Call graph
train_and_write calls assert, bin_t, bins, cost, first, flag_value, infer, input_output_pairs, inputs, shuffle, intrinsic_array_t, last, mini_batches, network_outputs, num_inputs, num_outputs, output, perturbed_identity_network, random_init, random_numbers, string, string_t, train, values
output calls to_json, write_lines
perturbed_identity_network calls string_t, e