train_saturated_mixture_ratio – Fiats
train_saturated_mixture_ratio Program
173 statements
Source File
Uses
julienne_m
fiats_m
iso_fortran_env
saturated_mixing_ratio_m
This program trains a neural network to learn the saturated mixing ratio function of ICAR.
Calls
Variables
Type Attributes Name Initial
integer(kind=int64) :: clock_rate
type(command_line_t) :: command_line
integer(kind=int64) :: counter_end
integer(kind=int64) :: counter_start
type(string_t) :: network_file
Functions
pure function e(j, n) result(unit_vector)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: j
integer, intent(in) :: n
Return Value real, allocatable, (:)
function perturbed_identity_network(perturbation_magnitude, n) result(trainable_network)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: perturbation_magnitude
integer, intent(in) :: n(:)
Return Value type(trainable_network_t)
Subroutines
subroutine open_plot_file_for_appending(plot_file_name, plot_unit, previous_epoch, previous_clock)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: plot_file_name
integer, intent(out) :: plot_unit
integer, intent(out) :: previous_epoch
real, intent(out) :: previous_clock
subroutine output(trainable_network, file_name)
Arguments
Type Intent Optional Attributes Name
type(trainable_network_t), intent(in) :: trainable_network
type(string_t), intent(in) :: file_name
subroutine print_diagnostics(plot_file_unit, epoch, cost, clock, nodes)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: plot_file_unit
integer, intent(in) :: epoch
real, intent(in) :: cost
real, intent(in) :: clock
integer, intent(in) :: nodes(:)
Call graph
train_saturated_mixture_ratio calls bin_t, bins, call_julienne_assert, cost, desired_outputs, file_t, first, flag_value, infer, input_output_pairs, inputs, shuffle, last, mini_batches, network_outputs, nodes_per_layer, num_inputs, num_outputs, output_sizes, open_plot_file_for_appending, output, perturbed_identity_network, print_diagnostics, y, random_init, random_numbers, string, string_t, train, values
open_plot_file_for_appending calls file_t, string, string_t, lines
output calls to_json, write_lines
perturbed_identity_network calls string_t, e
y calls call_julienne_assert, values, saturated_mixing_ratio