name: CI

on: [push, pull_request]


jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-12, ubuntu-24.04]
      fail-fast: true
    env:
      FC: gfortran
      GCC_V: 14

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - uses: fortran-lang/setup-fpm@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install Dependencies MacOS
      if: contains(matrix.os, 'mac')
      run: |
        brew install gcc@${GCC_V}
        sudo ln -s $(which gfortran-${GCC_V}) $(dirname $(which gfortran-${GCC_V}))/gfortran

    - name: Install on Ubuntu
      if: contains(matrix.os, 'ubuntu')
      run: |
        sudo apt update
        sudo apt install -y build-essential gfortran-14 gcc-14 g++-14

    - name: Build and Test MacOS
      if: contains(matrix.os, 'mac')
      run: |
        export PATH="${HOME}/.local/bin:$PATH"
        ./setup.sh

    - name: Build and Test Ubuntu
      if: contains(matrix.os, 'ubuntu')
      run: |
        fpm --version
        export FPM_FC=gfortran-14
        export FPM_CC=gcc-14
        fpm test
