name: Build and Deploy Documentation

on: [push, pull_request]


jobs:
  Build:
    runs-on: ubuntu-latest

    env:
      FC: gfortran

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Dependencies Ubuntu
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        PATH=/home/linuxbrew/.linuxbrew/bin/:"$PATH"
        brew install ford gcc
        PATH=`brew --prefix ford`/bin:"$PATH"
    - name: Build Developer Documenation
      run: |
        ford ford.md
        cp ./README.md ./doc/html
    - name: Upload Documentation
      uses: actions/upload-artifact@v2
      with:
        name: documentation
        path: doc/html
        if-no-files-found: error

    - name: Broken Link Check
      if: ${{ github.ref == 'refs/heads/main'}}
      uses: technote-space/broken-link-checker-action@v1
      with:
        TARGET: file://${{ github.workspace }}/doc/html/index.html
        RECURSIVE: true
        ASSIGNEES: ${{ github.actor }}

    - name: Deploy API Documentation
      uses: JamesIves/github-pages-deploy-action@4.1.0
      if: ${{ github.event_name == 'push'  &&  github.ref == 'refs/heads/main' }}
      with:
        branch: gh-pages
        folder: doc/html
